pool:
  vmImage: 'Ubuntu 18.04'

trigger:
- master

pr:
- master

variables:
  buildConfiguration: 'Debug'

steps:
- task: UseDotNet@2  
  inputs:    
    version: '6.x'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: 'src/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:    
    command: 'build'
    projects: 'src/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: 'test/*.csproj'
    arguments: '--collect:"XPlat Code Coverage"'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/*/coverage.cobertura.xml'
    pathToSources: 'src/'
    reportDirectory: 'report/'